#!/bin/bash

# Run /bin/bash ./build

APPS_JSON_BASE64=$(openssl base64 -in ./docker/apps.json)

docker build \
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=version-15 \
  --build-arg=PYTHON_VERSION=3.11.6 \
  --build-arg=NODE_VERSION=18.18.2 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=ghcr.io/skaiworld/skai-erp:v15 \
  --file=docker/Dockerfile .

# export CR_PAT=YOUR_TOKEN
# echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
# docker push ghcr.io/skaiworld/skai-erp:v15
