name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set Apps JSON
        run: |
          echo "APPS_JSON_BASE64=$(base64 -w 0 docker/apps.json)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
            PYTHON_VERSION=3.11.6
            NODE_VERSION=18.18.2
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
          push: true
          tags: ghcr.io/${{ github.repository }}:v15
